trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello world!
  displayName: 'Testing...'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-azure'
    repository: 'niallc18/testing-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Niall Canning DevOps(bba40194-a5aa-4186-8a79-bc6a95b291fa)'
    azureResourceGroup: 'networking-rg'
    kubernetesCluster: 'terraform-aks-cluster'
    manifests: 'application-manifest.yaml'